export const INDIAN_BANKS = [
  "State Bank of India (SBI)",
  "HDFC Bank",
  "ICICI Bank",
  "Axis Bank",
  "Punjab National Bank (PNB)",
  "Kotak Mahindra Bank",
  "Bank of Baroda",
  "Canara Bank",
  "Union Bank of India",
  "Yes Bank",
  "IDBI Bank",
  "IDFC First Bank",
  "IndusInd Bank",
  "Federal Bank",
  "RBL Bank",
  "AU Small Finance Bank",
  "Bandhan Bank",
  "Central Bank of India",
  "Indian Bank",
  "UCO Bank",
  "Bank of India",
  "Bank of Maharashtra",
  "Karnataka Bank",
  "South Indian Bank",
  "DBS Bank",
  "HSBC",
  "Standard Chartered",
  "Citi Bank",
  "Paytm Payments Bank",
  "Airtel Payments Bank",
  "Jio Payments Bank",
  "Fino Payments Bank",
  "India Post Payments Bank",
  "Karur Vysya Bank",
  "Tamilnad Mercantile Bank",
  "Jammu & Kashmir Bank",
  "Punjab & Sind Bank",
  "Dhanlaxmi Bank",
  "CSB Bank",
  "DCB Bank",
];
